import {
  type RouteConfig,
  index,
  prefix,
  route,
} from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  ...prefix("accounts", [
    route("add-email", "routes/accounts/add-email.tsx"),
    route("change-email", "routes/accounts/change-email.tsx"),
    route("forgot-password", "routes/accounts/forgot-password.tsx"),
    route("login", "routes/accounts/login.tsx"),
    route("logout", "routes/accounts/logout.tsx"),
    route("onboarding", "routes/accounts/onboarding.tsx"),
    route("onboarding/social", "routes/accounts/onboarding.social.tsx"),
    route("password", "routes/accounts/password.tsx"),
    route("reset-password", "routes/accounts/reset-password.tsx"),
    route("signup", "routes/accounts/signup.tsx"),
    route("user/delete", "routes/accounts/user.delete.tsx"),
    route("verify", "routes/accounts/verify.tsx"),
  ]),
  ...prefix("api", [
    route("agree-to-terms", "routes/api/agree-to-terms.ts"),
    route("bluesky/status", "routes/api/bluesky.status.ts"),
    route("link/update-metadata", "routes/api/link.update-metadata.ts"),
    route("list/subscribe", "routes/api/list.subscribe.ts"),
    route("mute/add", "routes/api/mute.add.ts"),
    route("mute/delete", "routes/api/mute.delete.ts"),
    route("polar/webhook", "routes/api/polar.webhook.ts"),
  ]),
  ...prefix("bluesky", [
    route("auth", "routes/bluesky/auth.ts"),
    route("auth/callback", "routes/bluesky/auth.callback.ts"),
    route("auth/revoke", "routes/bluesky/auth.revoke.ts"),
  ]),
  ...prefix("bookmarks", [
    route("add", "routes/bookmarks/add.ts"),
    route("delete", "routes/bookmarks/delete.ts"),
    route("delete-tag", "routes/bookmarks/delete-tag.ts"),
    route("popup", "routes/bookmarks/popup.tsx"),
    index("routes/bookmarks/index.tsx"),
  ]),
  route("client-metadata.json", "routes/client-metadata.ts"),
  ...prefix("digest", [
    route(":userId/:feedItemId", "routes/digest/feedItem.tsx"),
    route(":userId.rss", "routes/digest/feed.tsx"),
    index("routes/digest/index.tsx"),
  ]),
  route("download", "routes/download.tsx"),
  ...prefix("email", [
    route("add", "routes/email/add.tsx"),
    route("delete", "routes/email/delete.tsx"),
    index("routes/email/index.tsx"),
  ]),
  route("jwks.json", "routes/jwks.ts"),
  ...prefix("links", [
    index("routes/links/index.tsx"),
    route("trending", "routes/links/trending.tsx"),
    route("domain/:domain", "routes/links/domain.tsx"),
    route("author/:author", "routes/links/author.tsx"),
    route("topic/:topic", "routes/links/topic.tsx"),
  ]),
  ...prefix("mastodon", [
    route("auth", "routes/mastodon/auth.ts"),
    route("auth/callback", "routes/mastodon/auth.callback.ts"),
    route("auth/revoke", "routes/mastodon/auth.revoke.ts"),
  ]),
  ...prefix("notifications", [
    index("routes/notifications/index.tsx"),
    route("delete", "routes/notifications/delete.ts"),
    route(":notificationGroupId.rss", "routes/notifications/feed.ts"),
    route("test", "routes/notifications/test.tsx"),
  ]),
  ...prefix("resources", [
    route("layout-switch", "routes/resources/layout-switch.tsx"),
    route("theme-switch", "routes/resources/theme-switch.tsx"),
  ]),
  ...prefix("settings", [
    index("routes/settings/index.tsx"),
    route("account", "routes/settings/account.tsx"),
    route("connections", "routes/settings/connections.tsx"),
    route("moderation", "routes/settings/moderation.tsx"),
    route("checkout", "routes/settings/checkout.tsx"),
    route("portal", "routes/settings/portal.tsx"),
    route("subscription", "routes/settings/subscription.tsx"),
  ]),
] satisfies RouteConfig;
